hero1 = ("BATMAN","BRUCE WAYNE")
hero2 = ("WONDER WOMAN","DIANA PRINCE")
new_tuple = (hero1,hero2)
print(new_tuple)
print (new_tuple[0])
print (new_tuple[1])
print (new_tuple[0][0])
print (new_tuple[0][1])
print (new_tuple[1][0])
print (new_tuple[1][1])